#!/bin/bash

# Configure build variables.
BUILD_MODE=Release
BUILD_ARCH=x64
BUILD_DIR=../build/clang-${BUILD_ARCH}-${BUILD_MODE}

# Color configuration.
COLOR_OFF='\033[0m'
COLOR_BLACK='\033[0;30m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_PURPLE='\033[0;35m'
COLOR_CYAN='\033[0;36m'
COLOR_WHITE='\033[0;37m'

PrintInfoMsg() {
	printf "${COLOR_GREEN} >> $1 ${COLOR_OFF}\n"
}

PrintErrorMsg() {
	printf "${COLOR_RED} >> $1 ${COLOR_OFF}\n"
}

CheckError() {
	if [ $? -eq 1 ]
	then
		PrintErrorMsg "$1"
		exit 1
	fi
}

PrintInfoMsg "Creating build directory if needed and go to it."

mkdir -p ${BUILD_DIR}
CheckError "Failed to generate project build directory."

cd ${BUILD_DIR}

PrintInfoMsg "Downloading the binary packages required for your configuration..."

conan install \
	--build missing \
	-s build_type=${BUILD_MODE} \
	../..
CheckError "Failed to download and install required conan packages."

PrintInfoMsg "Generating project via CMake..."

cmake \
	-G Xcode \
	"-DCMAKE_BUILD_TYPE:STRING=${BUILD_MODE}" \
	../..
CheckError "Failed to generating project via CMake."

PrintInfoMsg "Project has been generated successfully!"
